#!/bin/bash
db="iterable"

if [ "$ITERABLE_ENVIRONMENT" = "test" ]; then
    db="iterable_test"
fi

migrate -url "postgres://postgres@localhost:5432/$db?sslmode=disable&password=postgres" -path ./db/migrations $@
